sonar.projectKey=django-cicd
sonar.projectName=django-cicd
sonar.projectVersion=1.0
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.host.url=http://54.238.224.46:9000
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/*.pyc,**/tests/**
